### ISSUE TITLE
SECRET_KEY_BASEを環境変数から取る

### ISSUE THREAD

**Issue by Alicey0719** [TKYcraft/chisato#11]
imageに共通で内包しているのはあまり良くない気がする
https://railsguides.jp/security.html#%E7%8B%AC%E8%87%AA%E3%81%AEcredential
(master-keyが安全に管理されている状態であればバージョン管理して良いと書いてあるが、これはfork的なことを想定しているのかわからない)

RAILS_MASTER_KEYが変われば良いという認識で良いか？

**Comment by myosotis-dev** [comment]
SECRET_KEY_BASE と RAILS_MASTER_KEY を ENV で取る方針で #12 実装完了。
Deploy で問題がなければこちらは close 予定

**Comment by myosotis-dev** [comment]
上記方針で本番環境で問題が発生しなかったので close.
