### ISSUE TITLE
[Infrastructure] 本番環境の用意 phase.1

### ISSUE THREAD

**Issue by myosotis-dev** [TKYcraft/chisato#8]
## 概要
Production 環境の用意 m(_ _)m

## 詳細
- [x] ドメイン / 証明書の準備 (一旦test domain の下でok)
- [x] Deploy するワーカーの準備
- [x] Deploy

## この Issue で対象としないこと
やってもよいけど保留することをメモしておく
- K8s
- 自動Deploy
- 専用サブドメインの設定

**Comment by Alicey0719** [comment]
close
